canonical: https://fhir.demo.org/profiling
fhirVersion: [4.0.1]
FSHOnly: false
applyExtensionMetadataToRoot: false
status: active
license: CC-BY-4.0
version: 0.0.1
id: demo
name: DEMO
title: "DEMO Fhir Profiles"
description: "DEMO Fhir Profiles"
packageId: org.demo.fhir
copyrightYear: 2024+
releaseLabel: ci-build
menu:
  Home: index.html
  Artifacts: artifacts.html
publisher:
  name: DEMO FHIR
  url: https://nhealth.org