services:
  postgres:
    image: postgres:12
    container_name: medplum-postgres
    restart: always
    environment:
      - POSTGRES_USER=medplum
      - POSTGRES_PASSWORD=medplum
    volumes:
      - ./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf
      - ./postgres/:/docker-entrypoint-initdb.d/
    command: postgres -c config_file=/usr/local/etc/postgres/postgres.conf
    expose:
      - '5432'
  redis:
    image: redis:7
    container_name: medplum-redis
    restart: always
    command: redis-server --requirepass medplum
    expose:
      - '6379'
  medplum-server:
    container_name: medplum-server
    image: medplum/medplum-server:latest
    volumes:
      - ./medplum.config.json:/usr/src/medplum/packages/server/medplum.config.json
    ports:
      - '8103:8103'
  app:
    container_name: medplum-app
    build:
      context: ./app
    ports:
      - "3030:3030"