services:
  # first setup through configuration file and build step
  orthanc-server:
    container_name: othanc-server
    image: orthancteam/orthanc:24.7.1
    depends_on: [orthanc-postgres]
    restart: unless-stopped
    ports: ["4242:4242", "8042:8042"]
    volumes: ["orthanc-server:/var/lib/orthanc/db"]
    environment:
      VERBOSE_STARTUP: "true"
      VERBOSE_ENABLED: "true"
      ORTHANC__POSTGRESQL: |
        {
          "Host": "orthanc-postgres",
          "EnableVerboseLogs": true
        }
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_WEB__SERIES_METADATA: "Full"
      ORTHANC__DICOM_WEB__STUDIES_METADATA: "Full"
      ORTHANC__DICOM_WEB__METADATA_WORKER_THREADS_COUNT : "4"
      ORTHANC__AUTHENTICATION_ENABLED: "false"

  orthanc-postgres:
    container_name: othanc-postgres
    image: postgres:15
    restart: unless-stopped
    expose:
      - '5432'
    volumes: ["orthanc-postgres:/var/lib/postgresql/data"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"


volumes:
  orthanc-server:
  orthanc-postgres: