server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
spring:
  main:
    allow-circular-references: true
    #allow-bean-definition-overriding: true
  flyway:
    enabled: false
    baselineOnMigrate: true
    fail-on-missing-locations: false
  datasource:
    url: jdbc:postgresql://192.168.16.2:5432/hapi
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    # database connection pool size
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate.format_sql: false
      hibernate.show_sql: false

      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hibernate.search.enabled: true
hapi:
  fhir:
    indexer:
      lucene:
        sync-writes: true
    cr:
      enabled: false

    reindex_enabled: true

    cdshooks:
      enabled: true
      clientIdHeaderName: client_id

    openapi_enabled: true
    fhir_version: R5

    ig_runtime_upload_enabled: false

    advanced_lucene_indexing: false
    bulk_export_enabled: false
    bulk_import_enabled: false

    narrative_enabled: false
    mdm_enabled: false
    mdm_rules_json_location: "mdm-rules.json"

    logical_urls:
      - http://terminology.hl7.org/*
      - https://terminology.hl7.org/*
      - http://snomed.info/*
      - https://snomed.info/*
      - http://unitsofmeasure.org/*
      - https://unitsofmeasure.org/*
      - http://loinc.org/*
      - https://loinc.org/*

    cors:
      allow_Credentials: true
      allowed_origin:
        - '*'

    search-coord-core-pool-size: 20
    search-coord-max-pool-size: 100
    search-coord-queue-capacity: 200

    tester:
      home:
        name: Local Tester
        server_address: 'http://localhost:8080/fhir'
        refuse_to_fetch_third_party_urls: false
        fhir_version: R5

    inline_resource_storage_below_size: 4000